### PR TITLE
Allow for Adestra link labels

### PR DESCRIPTION
**Pull request by jwade1327**

### CODE REVIEW

**Comment by Shinsina** [comment]
[Link Labels for newsletter templates](https://trello.com/c/5xiNwopA/220-link-labels-for-newsletter-templates)

**Comment by Shinsina** [comment]
I have a PR out against this branch in order to put a "platform designator" on the link labels as well as adding link labels to all promotions and advertisements, please review here: https://github.com/jwade1327/ascend-media-newsletters/pull/1 let me know if you have any questions.

**Comment by jwade1327** [comment]
@Shinsina do I need to do anything on my end since you have a branch off of mine? I just changed the status from 'draft'. Let me know thanks!

**Comment by Shinsina** [comment]
@jwade1327 Review and merge the PR I have out against your branch here: https://github.com/jwade1327/ascend-media-newsletters/pull/1 if you have any questions or suggestions let me know.

**Comment by Shinsina** [comment]
The only thing I think warrants some sort of discussion is if the numbering should be based off the slot number or the number of items actually showing up. (Say if certain ad positions don't populate should slot 4 be numbered as 4 even if only 2 ads show up total)

**Comment by jwade1327** [comment]
@B77Mills I just merged Jake's changes we talked about this morning into my branch.

**Review by B77Mills — APPROVED** [review]

**Pull request merged**
