### PR TITLE
Create AHA Hypertension Registered and Non-Registered newsletters

### PR DESCRIPTION
**Pull request by jwade1327**

### CODE REVIEW

**Comment by jwade1327** [comment]
Once merged I can update the template files to use the aha-footer

**Comment by jwade1327** [comment]
[Phase 1: AHA - Hypertension eNewsletter Initial Setup](https://trello.com/c/gN9fu4CT/165-phase-1-aha-hypertension-enewsletter-initial-setup)

**Comment by jwade1327** [comment]
Not sure why Travis failed. I tried to rerun Travis (got the confirmation that I successfully requested to rerun), but it hasn't done so.

**Comment by Shinsina** [comment]
> Not sure why Travis failed. I tried to rerun Travis (got the confirmation that I successfully requested to rerun), but it hasn't done so.



> Not sure why Travis failed. I tried to rerun Travis (got the confirmation that I successfully requested to rerun), but it hasn't done so.

Screen Shot 2021-08-19 at 3 27 37 PM

**Pull request closed without merging**
